# Generated by Django 5.0.7 on 2024-08-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_jwt_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='jwt_key',
        ),
    ]
