# Generated by Django 5.0.7 on 2024-07-31 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snowflake_id', models.BigIntegerField(unique=True)),
                ('short_url', models.CharField(max_length=50, unique=True)),
                ('long_url', models.URLField(db_index=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
