# Generated by Django 5.0.7 on 2024-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='long_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='shortner',
            name='short_url',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
