# Generated by Django 5.0.7 on 2024-08-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortner_long_url_alter_shortner_short_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortner',
            new_name='Shortener',
        ),
    ]
