name: Django application

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker
        run: docker compose build
      - name: Run ruff
        run: docker compose run django ruff check urlshortener/
      - name: Run tests
        run: docker compose run django py.test

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
          cache: "pip"
          cache-dependency-path: |
            requirements/local.txt
            requirements/base.txt
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/Python/3.12.4/x64/ # This path is specific to Ubuntu
          key: python-${{ hashFiles('requirements/local.txt') }}-${{ hashFiles('requirements/base.txt') }}
      - name: Install dependencies
        run: pip install -r requirements/local.txt
      - name: Run ruff
        run: ruff check .
      - name: Run tests
        run: pytest
